//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectingManySerials
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialD
    {
        public string SerialM { get; set; }
        public int SerialDId { get; set; }
        public string SerialD1 { get; set; }
        public Nullable<System.DateTime> UpdTime { get; set; }
    }
}
